export const patientSearchStringsEn = {
    title: "Patient search",
    dobLabel: "Date of Birth",
    dobPlaceholder: "MM/DD/YYYY",
    patientIdLabel: "Patient ID",
    patientIdPlaceholder: "######",
    firstNameLabel: "First Name",
    firstNamePlaceholder: "Start typing first name...",
    middleNameLabel: "Middle Name",
    middleNamePlaceholder: "Start typing middle name...",
    lastNameLabel: "Last Name",
    lastNamePlaceholder: "Start typing last name...",
    expandSearchBtn: "Expand search",
    collapseSearchBtn: "Collapse search",
}